#!/bin/sh

rsync -rav --delete \
	--exclude '.*' \
	--exclude node_modules \
	. 'root@vbb-web.jannisr.de:~/vbb-web/'

ssh 'root@vbb-web.jannisr.de' "\
cd ~/vbb-web
npm i
export NODE_ENV=production
forever stop vbb-web
forever start -a --uid vbb-web app.js"
